<?php
/*

By Dimitri Kafetzi @ http://www.kafetzisd.gr
Distributed under the Creative Commons Attribution 3.0 License

*/
?>
<!-- portofolio section -->
	<div id="portofolio_section_wrapper">
		<section id="portofolio_section">
			<nav id="filter">
				<!-- The menu items will go here (generated by jQuery) -->
			</nav>
			
			<section id="container">
				<ul id="stage">
					<!-- Your portfolio items go here -->
					<li data-tags="Ομάδα,Φωτογραφία" class="clearfix">
						<figure>
							<img src="./media/pictures/Unmanned-Evolution-Tshirts_small.png"/>
						</figure>
					</li>
					<li data-tags="Πολύπτερο,Ομάδα,Φωτογραφία" class="clearfix">
						<figure>
							<img src="./media/pictures/multicopter-on-hands_small.png" />
						</figure>
					</li>
					<li data-tags="Πολύπτερο,Φωτογραφία,Εναέρια φωτογραφία,Allu fan park,Συνεργάτες,Αθήνα,Raw υλικό,Nex 5,Συναυλίες" class="clearfix">
						<figure>
							<img src="./media/pictures/Unmanned-Evolution-Tshirts_small.png" />
						</figure>
					</li>
					<li data-tags="Πολύπτερο,Φωτογραφία,Εναέρια φωτογραφία,Allu fan park,Συνεργάτες,Αθήνα,Raw υλικό,Nex 5,Συναυλίες" class="clearfix">
						<figure>
							<img src="./media/pictures/Unmanned-Evolution-Tshirts_small.png" />
						</figure>
					</li>
					<li data-tags="Πολύπτερο,Φωτογραφία,Εναέρια φωτογραφία,Allu fan park,Συνεργάτες,Αθήνα,Raw υλικό,Nex 5,Συναυλίες" class="clearfix">
						<figure>
							<img src="./media/pictures/Unmanned-Evolution-Tshirts_small.png" />
						</figure>
					</li>
					<li data-tags="Πολύπτερο,Φωτογραφία,Εναέρια φωτογραφία,Allu fan park,Συνεργάτες,Αθήνα,Raw υλικό,Nex 5,Συναυλίες" class="clearfix">
						<figure>
							<img src="./media/pictures/Unmanned-Evolution-Tshirts_small.png" />
						</figure>
					</li>
					<li data-tags="Πολύπτερο,Φωτογραφία,Εναέρια φωτογραφία,Allu fan park,Συνεργάτες,Αθήνα,Raw υλικό,Nex 5,Συναυλίες" class="clearfix">
						<figure>
							<img src="./media/pictures/Unmanned-Evolution-Tshirts_small.png" />
						</figure>
					</li>
					<li data-tags="Πολύπτερο,Φωτογραφία,Εναέρια φωτογραφία,Allu fan park,Συνεργάτες,Αθήνα,Raw υλικό,Nex 5,Συναυλίες" class="clearfix">
						<figure>
							<img src="./media/pictures/Unmanned-Evolution-Tshirts_small.png" />
						</figure>
					</li>
					<li data-tags="Πολύπτερο,Φωτογραφία,Εναέρια φωτογραφία,Allu fan park,Συνεργάτες,Αθήνα,Raw υλικό,Nex 5,Συναυλίες" class="clearfix">
						<figure>
							<img src="./media/pictures/Unmanned-Evolution-Tshirts_small.png" />
						</figure>
					</li>
					<li data-tags="Πολύπτερο,Φωτογραφία,Εναέρια φωτογραφία,Allu fan park,Συνεργάτες,Αθήνα,Raw υλικό,Nex 5,Συναυλίες" class="clearfix">
						<figure>
							<img src="./media/pictures/Unmanned-Evolution-Tshirts_small.png" />
						</figure>
					</li>
					<li data-tags="Πολύπτερο,Φωτογραφία,Εναέρια φωτογραφία,Allu fan park,Συνεργάτες,Αθήνα,Raw υλικό,Nex 5,Συναυλίες" class="clearfix">
						<figure>
							<img src="./media/pictures/Unmanned-Evolution-Tshirts_small.png" />
						</figure>
					</li>
					<li data-tags="Πολύπτερο,Φωτογραφία,Εναέρια φωτογραφία,Allu fan park,Συνεργάτες,Αθήνα,Raw υλικό,Nex 5,Συναυλίες" class="clearfix">
						<figure>
							<img src="./media/pictures/Unmanned-Evolution-Tshirts_small.png" />
						</figure>
					</li>
					<li data-tags="Πολύπτερο,Φωτογραφία,Εναέρια φωτογραφία,Allu fan park,Συνεργάτες,Αθήνα,Raw υλικό,Nex 5,Συναυλίες" class="clearfix">
						<figure>
							<img src="./media/pictures/Unmanned-Evolution-Tshirts_small.png" />
						</figure>
					</li>
					<li data-tags="Πολύπτερο,Φωτογραφία,Εναέρια φωτογραφία,Allu fan park,Συνεργάτες,Αθήνα,Raw υλικό,Nex 5,Συναυλίες" class="clearfix">
						<figure>
							<img src="./media/pictures/Unmanned-Evolution-Tshirts_small.png" />
						</figure>
					</li>
					<li data-tags="Πολύπτερο,Φωτογραφία,Εναέρια φωτογραφία,Allu fan park,Συνεργάτες,Αθήνα,Raw υλικό,Nex 5,Συναυλίες" class="clearfix">
						<figure>
							<img src="./media/pictures/Unmanned-Evolution-Tshirts_small.png" />
						</figure>
					</li>
					<li data-tags="Πολύπτερο,Φωτογραφία,Εναέρια φωτογραφία,Allu fan park,Συνεργάτες,Αθήνα,Raw υλικό,Nex 5,Συναυλίες" class="clearfix">
						<figure>
							<img src="./media/pictures/Unmanned-Evolution-Tshirts_small.png" />
						</figure>
					</li>
					<li data-tags="Πολύπτερο,Φωτογραφία,Εναέρια φωτογραφία,Allu fan park,Συνεργάτες,Αθήνα,Raw υλικό,Nex 5,Συναυλίες" class="clearfix">
						<figure>
							<img src="./media/pictures/Unmanned-Evolution-Tshirts_small.png" />
						</figure>
					</li>
					<li data-tags="Πολύπτερο,Ομάδα,Φωτογραφία" class="clearfix">
						<figure>
							<img src="./media/pictures/multicopter-on-hands_small.png" />
						</figure>
					</li>
					<li data-tags="Ομάδα,Φωτογραφία" class="clearfix">
						<figure class="clearfix">
							<img src="./media/pictures/Unmanned-Evolution-Tshirts_small.png" />
						</figure>
					</li>
					<li data-tags="Video,Εναέρια Κινηματογράφηση" class="clearfix">
						<figure>
							<video id="services_aerialvideo_trailer">
								<source type="video/youtube" src="http://www.youtube.com/embed/AxmMFyiJ8uA">
							</video>
						</figure>
					</li>
				</ul>
			</section>
		</section>
	</div>